// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sport_calendar.dal.Context;

#nullable disable

namespace sport_calendar.dal.Migrations
{
    [DbContext(typeof(ExerciseDbContext))]
    partial class ExerciseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("sport_calendar.dal.Entities.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("PK__activity__3213E83F71BBA419");

                    b.ToTable("activity_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Walking"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Running"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cycling"
                        });
                });

            modelBuilder.Entity("sport_calendar.dal.Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("StatusLabel")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("status_label");

                    b.HasKey("Id")
                        .HasName("PK__statuses__3213E83F30F9A01E");

                    b.ToTable("statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            StatusLabel = "Planned"
                        },
                        new
                        {
                            Id = 2,
                            StatusLabel = "In Progress"
                        },
                        new
                        {
                            Id = 3,
                            StatusLabel = "Completed"
                        });
                });

            modelBuilder.Entity("sport_calendar.dal.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("unit_code");

                    b.HasKey("Id")
                        .HasName("PK__units__3213E83F59CECF32");

                    b.ToTable("units", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UnitCode = "steps"
                        },
                        new
                        {
                            Id = 2,
                            UnitCode = "km"
                        },
                        new
                        {
                            Id = 3,
                            UnitCode = "min"
                        });
                });

            modelBuilder.Entity("sport_calendar.dal.Entities.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityId")
                        .HasColumnType("int")
                        .HasColumnName("activity_id");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("status_id");

                    b.Property<DateOnly>("WorkoutDate")
                        .HasColumnType("date")
                        .HasColumnName("workout_date");

                    b.HasKey("Id")
                        .HasName("PK__workouts__3213E83FE82A5192");

                    b.HasIndex("ActivityId");

                    b.HasIndex("StatusId");

                    b.ToTable("workouts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityId = 1,
                            StatusId = 2,
                            WorkoutDate = new DateOnly(2026, 2, 24)
                        },
                        new
                        {
                            Id = 2,
                            ActivityId = 2,
                            StatusId = 1,
                            WorkoutDate = new DateOnly(2026, 2, 24)
                        },
                        new
                        {
                            Id = 3,
                            ActivityId = 3,
                            StatusId = 1,
                            WorkoutDate = new DateOnly(2026, 2, 25)
                        });
                });

            modelBuilder.Entity("sport_calendar.dal.Entities.WorkoutGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("TargetValue")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("target_value");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("unit_id");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int")
                        .HasColumnName("workout_id");

                    b.HasKey("Id")
                        .HasName("PK__workout___3213E83F9E883FD9");

                    b.HasIndex("UnitId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("workout_goals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TargetValue = 10000m,
                            UnitId = 1,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 2,
                            TargetValue = 7.5m,
                            UnitId = 2,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 3,
                            TargetValue = 5.0m,
                            UnitId = 2,
                            WorkoutId = 2
                        },
                        new
                        {
                            Id = 4,
                            TargetValue = 45m,
                            UnitId = 3,
                            WorkoutId = 3
                        });
                });

            modelBuilder.Entity("sport_calendar.dal.Entities.WorkoutMetric", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("MetricValue")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("metric_value");

                    b.Property<DateTime?>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UnitId")
                        .HasColumnType("int")
                        .HasColumnName("unit_id");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int")
                        .HasColumnName("workout_id");

                    b.HasKey("Id")
                        .HasName("PK__workout___3213E83F752132BD");

                    b.HasIndex("UnitId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("workout_metrics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MetricValue = 2000m,
                            UnitId = 1,
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 2,
                            MetricValue = 1.4m,
                            UnitId = 2,
                            WorkoutId = 1
                        });
                });

            modelBuilder.Entity("sport_calendar.dal.Entities.Workout", b =>
                {
                    b.HasOne("sport_calendar.dal.Entities.ActivityType", "Activity")
                        .WithMany("Workouts")
                        .HasForeignKey("ActivityId")
                        .IsRequired()
                        .HasConstraintName("FK_Workouts_Activity");

                    b.HasOne("sport_calendar.dal.Entities.Status", "Status")
                        .WithMany("Workouts")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Workouts_Status");

                    b.Navigation("Activity");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("sport_calendar.dal.Entities.WorkoutGoal", b =>
                {
                    b.HasOne("sport_calendar.dal.Entities.Unit", "Unit")
                        .WithMany("WorkoutGoals")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_Goals_Unit");

                    b.HasOne("sport_calendar.dal.Entities.Workout", "Workout")
                        .WithMany("WorkoutGoals")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Goals_Workout");

                    b.Navigation("Unit");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("sport_calendar.dal.Entities.WorkoutMetric", b =>
                {
                    b.HasOne("sport_calendar.dal.Entities.Unit", "Unit")
                        .WithMany("WorkoutMetrics")
                        .HasForeignKey("UnitId")
                        .IsRequired()
                        .HasConstraintName("FK_Metrics_Unit");

                    b.HasOne("sport_calendar.dal.Entities.Workout", "Workout")
                        .WithMany("WorkoutMetrics")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Metrics_Workout");

                    b.Navigation("Unit");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("sport_calendar.dal.Entities.ActivityType", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("sport_calendar.dal.Entities.Status", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("sport_calendar.dal.Entities.Unit", b =>
                {
                    b.Navigation("WorkoutGoals");

                    b.Navigation("WorkoutMetrics");
                });

            modelBuilder.Entity("sport_calendar.dal.Entities.Workout", b =>
                {
                    b.Navigation("WorkoutGoals");

                    b.Navigation("WorkoutMetrics");
                });
#pragma warning restore 612, 618
        }
    }
}
